swagger: '2.0'
info:
  description: defaultDescription
  version: '0.1'
  title: JsonGeneratorClient
paths:
  /api/atlas_lineage_create:
    post:
      operationId: createLineageData
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Request'
          x-examples:
            application/json: >-
              { "name": "derived_from_col_dq", "type_name": "derived_from_col",
              "qualified_name":
              "process/derived_from_col/dqrule/azure_sql_column", "created_by":
              "sg", "process_attributes": [{"attr_name": "StartTime",
              "attr_value": "10:40:09", "is_entityref": false}, {"attr_name":
              "EndTime", "attr_value": "10:50:09", "is_entityref": false}],
              "inputs": [{"guid": "ddb2bc49-af2a-41e3-9b26-0c6bec90e0d6",
              "typeName": "azure_sql_column_sg"}], "outputs": [{"guid":
              "faf02429-9fbf-4d97-b0d9-35a8dd6887bd", "typeName": "DQ_Rule_1"},
              {"guid": "674aeda1-6f7d-4d61-9910-188b9050ed52", "typeName":
              "DQ_Rule_1"}]}
      responses:
        '200':
          description: Definition generated from Swagger Inspector
          schema:
            $ref: '#/definitions/Response'
definitions:
  Process_attributes:
    properties:
      attr_name:
        type: string
      attr_value:
        type: string
      is_entityref:
        type: boolean
  Inputs:
    properties:
      guid:
        type: string
      typeName:
        type: string
  Outputs:
    properties:
      guid:
        type: string
      typeName:
        type: string
  Request:
    properties:
      name:
        type: string
      type_name:
        type: string
      qualified_name:
        type: string
      created_by:
        type: string
      process_attributes:
        type: array
        items:
          $ref: '#/definitions/Process_attributes'
      inputs:
        type: array
        items:
          $ref: '#/definitions/Inputs'
      outputs:
        type: array
        items:
          $ref: '#/definitions/Outputs'
  Attributes_Inputs:
    properties:
      guid:
        type: string
      typeName:
        type: string
  Attributes_Outputs:
    properties:
      guid:
        type: string
      typeName:
        type: string
  Attributes:
    properties:
      inputs:
        type: array
        items:
          $ref: '#/definitions/Attributes_Inputs'
      outputs:
        type: array
        items:
          $ref: '#/definitions/Attributes_Outputs'
      qualifiedName:
        type: string
      name:
        type: string
      StartTime:
        type: string
      EndTime:
        type: string
  Entities:
    properties:
      typeName:
        type: string
      guid:
        type: integer
        format: int32
      createdBy:
        type: string
      attributes:
        $ref: '#/definitions/Attributes'
  Response:
    properties:
      entities:
        type: array
        items:
          $ref: '#/definitions/Entities'